GET http://localhost:3001/api/users
###
GET http://localhost:3001/api/users/1
###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "nguyen",
    "password": "0123456"
}